services:
  web:
    build: satellite_project
    image: satellite-project-image
    container_name: satellite-project-container
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
   image: "redis:alpine"
   container_name: redis-container
   restart: unless-stopped
   ports:
     - "6379:6379"
  vue:
    build: vue-frontend-project
    container_name: vue-frontend-container
    ports:
      - "8080:8080"
    depends_on:
      - web
