# Generated by Django 5.1 on 2024-08-15 03:13

import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spacecraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('status', models.CharField(choices=[('NOMINAL', 'NOMINAL'), ('MALFUNCTIONING', 'MALFUNCTIONING')], default='NOMINAL', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('Satellites', models.ManyToManyField(to='simulation_app.spacecraft')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
